services:
  db:
    container_name: '${HOST_NAME}'
    image: postgres:16.3-alpine3.20
    ports: 
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - proto-data:/val/lib/postgres/data
      - ./script:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    environment:
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_USER_PW}'
      - 'POSTGRES_DB=${DB_NAME}'
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${DB_USER} -d ${DB_NAME} -f docker-entrypoint-initdb.d/init.sql"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 2s 
    restart: unless-stopped
  web:
    container_name: proto_web
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./:/app
    restart: unless-stopped
volumes:
  proto-data:
